:begin
CREATE CONSTRAINT ON (node:Genre) ASSERT (node.name) IS UNIQUE;
CREATE CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
:commit
CALL db.awaitIndexes(300);
:begin
UNWIND [{_id:9, properties:{password:"$2b$10$Ff7sQ9yIHij.gK4ZWHDlTOjlWvhNXXziTaBoWNb1YZS6moN8DnZdu", salt:"$2b$10$Ff7sQ9yIHij.gK4ZWHDlTO", username:"Maksimilijan96"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:User;
UNWIND [{_id:82, properties:{name:"Nuthin' but a 'G' Thang", views:0, songUrl:"https://www.youtube.com/embed/6xjRdBjmePQ"}}, {_id:86, properties:{name:"The Way I Am", views:0, songUrl:"https://www.youtube.com/embed/LsETLMmvd2M"}}, {_id:87, properties:{name:"Bitch Please II", views:0, songUrl:"https://www.youtube.com/embed/tEMA8GL-ArI"}}, {_id:88, properties:{name:"Stan", views:0, songUrl:"https://www.youtube.com/embed/DkO1wwIXQ1g"}}, {_id:89, properties:{name:"The Real Slim Shady", views:0, songUrl:"https://www.youtube.com/embed/Y8ZI1uc6iBM"}}, {_id:90, properties:{name:"Criminal", views:0, songUrl:"https://www.youtube.com/embed/mR8_ldc9lag"}}, {_id:91, properties:{name:"Kim", views:0, songUrl:"https://www.youtube.com/embed/-SeVN2u5Axc"}}, {_id:92, properties:{name:"Without Me", views:0, songUrl:"https://www.youtube.com/embed/tqxRidAWER8"}}, {_id:93, properties:{name:"Say What You Say", views:0, songUrl:"https://www.youtube.com/embed/8xNHdegQmIQ"}}, {_id:94, properties:{name:"White America", views:0, songUrl:"https://www.youtube.com/embed/vxpeKhbeLm0"}}, {_id:95, properties:{name:"Sing For The Moment", views:0, songUrl:"https://www.youtube.com/embed/D4hAVemuQXY"}}, {_id:96, properties:{name:"Till I Collapse", views:0, songUrl:"https://www.youtube.com/embed/Obim8BYGnOE"}}, {_id:97, properties:{name:"Not Afraid", views:0, songUrl:"https://www.youtube.com/embed/j5-yKhDd64s"}}, {_id:98, properties:{name:"Love The Way You Lie", views:0, songUrl:"https://www.youtube.com/embed/uelHwf8o7_U"}}, {_id:99, properties:{name:"Cinderella Man", views:0, songUrl:"https://www.youtube.com/embed/kKPZqkcWeTM"}}, {_id:100, properties:{name:"Space Bound", views:0, songUrl:"https://www.youtube.com/embed/n87huvGRErw"}}, {_id:101, properties:{name:"Won't Back Down", views:0, songUrl:"https://www.youtube.com/embed/hOFkhNijQeY"}}, {_id:102, properties:{name:"Let Me Ride", views:0, songUrl:"https://www.youtube.com/embed/yaRSO7uXciY"}}, {_id:103, properties:{name:"High Powered", views:0, songUrl:"https://www.youtube.com/embed/3KY9bO6K2so"}}, {_id:104, properties:{name:"'Lil' Ghetto Boy", views:0, songUrl:"https://www.youtube.com/embed/qO5ITgzJO2A"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:105, properties:{name:"Stranded on Death Row", views:0, songUrl:"https://www.youtube.com/embed/VzaPzrll7CQ"}}, {_id:106, properties:{name:"Still D.R.E.", views:0, songUrl:"https://www.youtube.com/embed/VzaPzrll7CQ"}}, {_id:107, properties:{name:"Forgot About DRE", views:0, songUrl:"https://www.youtube.com/embed/QFcv5Ma8u8k"}}, {_id:108, properties:{name:"The Next Episode", views:0, songUrl:"https://www.youtube.com/embed/QZXc39hT8t4"}}, {_id:109, properties:{name:"What's the Difference", views:0, songUrl:"https://www.youtube.com/embed/IbvP3oj3l80"}}, {_id:110, properties:{name:"Xxplosive", views:0, songUrl:"https://www.youtube.com/embed/rCJktMzpiR0"}}, {_id:111, properties:{name:"Gin and Juice", views:0, songUrl:"https://www.youtube.com/embed/Y_WxELxb4qI"}}, {_id:112, properties:{name:"What's My Name? (Snoop Doggy Dogg song)", views:0, songUrl:"https://www.youtube.com/embed/BZLZpAHFZYI"}}, {_id:113, properties:{name:"Tha Shiznit", views:0, songUrl:"https://www.youtube.com/embed/fjebEZmRDcg"}}, {_id:114, properties:{name:"Murder Was the Case", views:0, songUrl:"https://www.youtube.com/embed/oGFVySHbeqA"}}, {_id:115, properties:{name:"Doggy Dogg World", views:0, songUrl:"https://www.youtube.com/embed/QI6N5GBoevI"}}, {_id:116, properties:{name:"Vapors", views:0, songUrl:"https://www.youtube.com/embed/MwX1XfgjFok"}}, {_id:117, properties:{name:"Doggfather", views:0, songUrl:"https://www.youtube.com/embed/mhSfSnJLiEo"}}, {_id:118, properties:{name:"Groupie", views:0, songUrl:"https://www.youtube.com/embed/nsf_WHtuYJ8"}}, {_id:119, properties:{name:"When I Grow Up", views:0, songUrl:"https://www.youtube.com/embed/QglH9JEx1Ic"}}, {_id:120, properties:{name:"Snoop Bounce", views:0, songUrl:"https://www.youtube.com/embed/mc0juCU7GGs"}}, {_id:121, properties:{name:"Boss' Life", views:0, songUrl:"https://www.youtube.com/embed/gKS08HkGMA4"}}, {_id:122, properties:{name:"Imagine", views:0, songUrl:"https://www.youtube.com/embed/7yruoism8BM"}}, {_id:123, properties:{name:"Vato", views:0, songUrl:"https://www.youtube.com/embed/Inw7B2F6_Hc"}}, {_id:124, properties:{name:"Candy", views:0, songUrl:"https://www.youtube.com/embed/mKli0y-Xr-Q"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:125, properties:{name:"Crazy", views:0, songUrl:"https://www.youtube.com/embed/GflVCALGSLQ"}}, {_id:126, properties:{name:"Me Against The World", views:0, songUrl:"https://www.youtube.com/embed/Qg0RA0yWmjg"}}, {_id:127, properties:{name:"Dear Mama", views:0, songUrl:"https://www.youtube.com/embed/Mb1ZvUDvLDY"}}, {_id:128, properties:{name:"So Many Tears", views:0, songUrl:"https://www.youtube.com/embed/O6yZq-clWhI"}}, {_id:129, properties:{name:"Temptations", views:0, songUrl:"https://www.youtube.com/embed/tXSGwgs2qaM"}}, {_id:130, properties:{name:"If I Die 2Nite", views:0, songUrl:"https://www.youtube.com/embed/LDllENVj8Kk"}}, {_id:131, properties:{name:"All Eyez on Me", views:0, songUrl:"https://www.youtube.com/embed/zSzaplTFagQ"}}, {_id:132, properties:{name:"California Love", views:0, songUrl:"https://www.youtube.com/embed/4Eukl5_BD0w"}}, {_id:133, properties:{name:"2 of Amerikaz Most Wanted", views:0, songUrl:"https://www.youtube.com/embed/5KxEXjCsL1s"}}, {_id:134, properties:{name:"All About U", views:0, songUrl:"https://www.youtube.com/embed/Jn9tMkqhWd0"}}, {_id:135, properties:{name:"I Ain't Mad at Cha", views:0, songUrl:"https://www.youtube.com/embed/I3VlRCm89B0"}}, {_id:136, properties:{name:"Hail Mary", views:0, songUrl:"https://www.youtube.com/embed/osVWj4RSfCQ"}}, {_id:137, properties:{name:"To Live And Die In L.A.", views:0, songUrl:"https://www.youtube.com/embed/-X0dN9qmY78"}}, {_id:138, properties:{name:"Toss It Up", views:0, songUrl:"https://www.youtube.com/embed/1IzQmyCGT4g"}}, {_id:139, properties:{name:"Blasphemy", views:0, songUrl:"https://www.youtube.com/embed/n6on3lSEb7U"}}, {_id:140, properties:{name:"Krazy", views:0, songUrl:"https://www.youtube.com/embed/jVLb93vg6k0"}}, {_id:141, properties:{name:"Famous", views:0, songUrl:"https://www.youtube.com/embed/Lq2TmRzg19k"}}, {_id:142, properties:{name:"Saint Pablo", views:0, songUrl:"https://www.youtube.com/embed/w9rzz4pDFwA"}}, {_id:143, properties:{name:"Low Lights", views:0, songUrl:"https://www.youtube.com/embed/wj0C2oet2r0"}}, {_id:144, properties:{name:"Highlights", views:0, songUrl:"https://www.youtube.com/embed/AXz78NYL4r4"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:145, properties:{name:"Waves", views:0, songUrl:"https://www.youtube.com/embed/ML8Yq1Rd6I0"}}, {_id:146, properties:{name:"Heard 'Em Say", views:0, songUrl:"https://www.youtube.com/embed/elVF7oG0pQs"}}, {_id:147, properties:{name:"Diamonds from Sierra Leone", views:0, songUrl:"https://www.youtube.com/embed/4q7OpvvfjWs"}}, {_id:148, properties:{name:"Touch the Sky", views:0, songUrl:"https://www.youtube.com/embed/0IAmdL0t6qI"}}, {_id:149, properties:{name:"Sweat", views:0, songUrl:"https://www.youtube.com/embed/0s9NrfU-9VI"}}, {_id:150, properties:{name:"Where Them Girls At", views:0, songUrl:"https://www.youtube.com/embed/p4kVWCSzfK4"}}, {_id:151, properties:{name:"Titanium", views:0, songUrl:"https://www.youtube.com/embed/JRfuAukYTKg"}}, {_id:152, properties:{name:"Little Bad Girl", views:0, songUrl:"https://www.youtube.com/embed/9ha5ujHnYXg"}}, {_id:153, properties:{name:"I Can Only Imagine", views:0, songUrl:"https://www.youtube.com/embed/TSNerxNwWtU"}}, {_id:154, properties:{name:"Crank It Up", views:0, songUrl:"https://www.youtube.com/embed/yDs0kiQftwY"}}, {_id:155, properties:{name:"Who's That Chick?'", views:0, songUrl:"https://www.youtube.com/embed/EAc4zHEDd7o"}}, {_id:156, properties:{name:"I Gotta Feeling", views:0, songUrl:"https://www.youtube.com/embed/7DOEcUhAgLo"}}, {_id:157, properties:{name:"Gone", views:0, songUrl:"https://www.youtube.com/embed/TwPCaWQIJME"}}, {_id:158, properties:{name:"Gold Digger", views:0, songUrl:"https://www.youtube.com/embed/m3xQfdDqBL0"}}, {_id:159, properties:{name:"I Need Your Love", views:0, songUrl:"https://www.youtube.com/embed/USqra5JF0cU"}}, {_id:160, properties:{name:"We Found Love", views:0, songUrl:"https://www.youtube.com/embed/GchEVSx9XEA"}}, {_id:161, properties:{name:"Feel So Close", views:0, songUrl:"https://www.youtube.com/embed/6cFx-yrtHRY"}}, {_id:162, properties:{name:"Let's Go", views:0, songUrl:"https://www.youtube.com/embed/mSxkN6zuKE8"}}, {_id:163, properties:{name:"Drinking from the Bottle", views:0, songUrl:"https://www.youtube.com/embed/CqPU7NSVQwY"}}, {_id:164, properties:{name:"One Love", views:0, songUrl:"https://www.youtube.com/embed/qYfmFyqBOQ8"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:165, properties:{name:"Memories", views:0, songUrl:"https://www.youtube.com/embed/w4T5i7TZbR0"}}, {_id:166, properties:{name:"I Wanna Go Crazy", views:0, songUrl:"https://www.youtube.com/embed/zwV1ElnnA84"}}, {_id:167, properties:{name:"Summer", views:0, songUrl:"https://www.youtube.com/embed/McEoTIqoRKk"}}, {_id:168, properties:{name:"Outside", views:0, songUrl:"https://www.youtube.com/embed/MjEYCUJuh-g"}}, {_id:169, properties:{name:"Blame", views:0, songUrl:"https://www.youtube.com/embed/HJb0VYVtaNc"}}, {_id:170, properties:{name:"Under Control", views:0, songUrl:"https://www.youtube.com/embed/UGT6v4No9U8"}}, {_id:171, properties:{name:"Burnin", views:0, songUrl:"https://www.youtube.com/embed/RLRtClGyGgo"}}, {_id:172, properties:{name:"Wake Me Up", views:0, songUrl:"https://www.youtube.com/embed/5y_KJAg8bHI"}}, {_id:173, properties:{name:"You Make Me", views:0, songUrl:"https://www.youtube.com/embed/2GADx4Hy-Gg"}}, {_id:174, properties:{name:"Hey Brother", views:0, songUrl:"https://www.youtube.com/embed/YxIiPLVR6NA"}}, {_id:175, properties:{name:"Addicted To You", views:0, songUrl:"https://www.youtube.com/embed/CWx4i-TUdWo"}}, {_id:176, properties:{name:"Lay Me Down", views:0, songUrl:"https://www.youtube.com/embed/xjPB8BmNVzQ"}}, {_id:177, properties:{name:"Waiting For Love", views:0, songUrl:"https://www.youtube.com/embed/-ncIVUXZla8"}}, {_id:178, properties:{name:"The Days", views:0, songUrl:"https://www.youtube.com/embed/JDglMK9sgIQ"}}, {_id:179, properties:{name:"The Nights", views:0, songUrl:"https://www.youtube.com/embed/XmIgg9De9hY"}}, {_id:180, properties:{name:"Broken Arrows", views:0, songUrl:"https://www.youtube.com/embed/V6iKSUoUN48"}}, {_id:181, properties:{name:"For A Better Day", views:0, songUrl:"https://www.youtube.com/embed/Xq-knHXSKYY"}}, {_id:182, properties:{name:"Numb", views:0, songUrl:"https://www.youtube.com/embed/aYGwi_N0FC8"}}, {_id:183, properties:{name:"Right Now", views:0, songUrl:"https://www.youtube.com/embed/Kvz9eMJL6jM"}}, {_id:184, properties:{name:"Nobody's Business", views:0, songUrl:"https://www.youtube.com/embed/H4sICbJsqFI"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:185, properties:{name:"What Now", views:0, songUrl:"https://www.youtube.com/embed/veau65llg3g"}}, {_id:186, properties:{name:"Diamonds", views:0, songUrl:"https://www.youtube.com/embed/kOGBIbqXwYE"}}, {_id:187, properties:{name:"No Love Allowed", views:0, songUrl:"https://www.youtube.com/embed/JlvjnAS4oYU"}}, {_id:188, properties:{name:"What's My Name?", views:0, songUrl:"https://www.youtube.com/embed/U0CGsw6h60k"}}, {_id:189, properties:{name:"California King Bed", views:0, songUrl:"https://www.youtube.com/embed/SfV4id78mTo"}}, {_id:190, properties:{name:"Only Girl (In The World)", views:0, songUrl:"https://www.youtube.com/embed/pa14VNsdSYM"}}, {_id:191, properties:{name:"Fading", views:0, songUrl:"https://www.youtube.com/embed/PeqrejRcChs"}}, {_id:192, properties:{name:"Skin", views:0, songUrl:"https://www.youtube.com/embed/P9cYF7kIlEQ"}}, {_id:193, properties:{name:"Umbrella", views:0, songUrl:"https://www.youtube.com/embed/xXD5tltX9Pg"}}, {_id:194, properties:{name:"Don't Stop The Music", views:0, songUrl:"https://www.youtube.com/embed/C75J03JXz24"}}, {_id:195, properties:{name:"Rehab", views:0, songUrl:"https://www.youtube.com/embed/RT_FfJPprO0"}}, {_id:196, properties:{name:"Shut Up And Drive", views:0, songUrl:"https://www.youtube.com/embed/VUNU9mep9Lg"}}, {_id:197, properties:{name:"Hate That I Love You", views:0, songUrl:"https://www.youtube.com/embed/9CEpgUv2po0"}}, {_id:198, properties:{name:"Thriller", views:0, songUrl:"https://www.youtube.com/embed/Z85lxckrtzg"}}, {_id:199, properties:{name:"Beat It", views:0, songUrl:"https://www.youtube.com/embed/kOn-HdEg6AQ"}}, {_id:200, properties:{name:"Billie Jean", views:0, songUrl:"https://www.youtube.com/embed/Kr4EQDVETuA"}}, {_id:201, properties:{name:"Wanna Be Startin' Somethin", views:0, songUrl:"https://www.youtube.com/embed/8KWf_-ofYgI"}}, {_id:202, properties:{name:"The Girl Is Mine", views:0, songUrl:"https://www.youtube.com/embed/8GB9BULxZ8c"}}, {_id:203, properties:{name:"Bad", views:0, songUrl:"https://www.youtube.com/embed/dIQmcwSg0nU"}}, {_id:204, properties:{name:"Smooth Criminal", views:0, songUrl:"https://www.youtube.com/embed/_mMyPJSx8RU"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{_id:205, properties:{name:"Dirty Diana", views:0, songUrl:"https://www.youtube.com/embed/aUD0juRwb3I"}}, {_id:206, properties:{name:"Leave Me Alone", views:0, songUrl:"https://www.youtube.com/embed/5XfDtxYv5AU"}}, {_id:207, properties:{name:"Man in the Mirror", views:0, songUrl:"https://www.youtube.com/embed/Z9NYDgbKsBE"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Song;
UNWIND [{name:"Metal", properties:{}}, {name:"Reggae", properties:{}}, {name:"Hip-hop", properties:{}}, {name:"Rock n roll", properties:{}}, {name:"Pop", properties:{}}, {name:"Electronic", properties:{}}] AS row
CREATE (n:Genre{name: row.name}) SET n += row.properties;
UNWIND [{_id:5, properties:{country:"USA", name:"Guns N Roses", type:"Band"}}, {_id:7, properties:{country:"UK", name:"UB40", type:"Band"}}, {_id:23, properties:{country:"UK", name:"Paul McCartney", type:"Solo"}}, {_id:25, properties:{country:"USA", name:"Metallica", type:"Band"}}, {_id:26, properties:{country:"UK", name:"Iron Maiden", type:"Band"}}, {_id:27, properties:{country:"USA", imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5k1yM2qEQh3i1ACtzq0JG2NHltmaVwc14DhBuAqglNkC-Pn0I&usqp=CAU", name:"Michael Jackson", type:"Solo"}}, {_id:28, properties:{country:"Ireland", name:"U2", type:"Band"}}, {_id:29, properties:{country:"UK", name:"Beatles", type:"Band"}}, {_id:31, properties:{country:"UK", name:"Rolling stones", type:"Band"}}, {_id:32, properties:{country:"USA", imageUrl:"https://www.dopmagazin.com/dop/wp-content/uploads/2020/03/Eminem-Chuff-Media.jpg", name:"Eminem", type:"Solo"}}, {_id:33, properties:{country:"USA", imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRt1ffXFcSu4_TQrz0XK-xfK-bAU5x-_eMg9S-ao-aN2pN4h-ku&usqp=CAU", name:"Rihanna", type:"Solo"}}, {_id:44, properties:{country:"USA", name:"Kanye West", type:"Solo"}}, {_id:45, properties:{country:"USA", name:"2Pac", type:"Solo"}}, {_id:46, properties:{country:"Jamaica", name:"Bob Marley", type:"Solo"}}, {_id:47, properties:{country:"Jamaica", name:"Inner Circle", type:"Band"}}, {_id:48, properties:{country:"Colombia", imageUrl:"https://i1.sndcdn.com/avatars-000754019632-3ewkg8-t500x500.jpg", name:"Shakira", type:"Solo"}}, {_id:50, properties:{country:"Australia", name:"ACDC", type:"Band"}}, {_id:51, properties:{country:"USA", name:"Dr Dre", type:"Solo"}}, {_id:53, properties:{country:"USA", name:"Snoop Dogg", type:"Solo"}}, {_id:55, properties:{country:"USA", imageUrl:"https://www.biography.com/.image/t_share/MTU0MTU0MTc3NzkzMTA3MzU1/beyonce-attends-tidal-x-1015-on-october-15-2016-in-new-york-city-photo-by-theo-wargogetty-images-for-tidal-sqaure.jpg", name:"Beyonce", type:"Solo"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Artist;
UNWIND [{_id:56, properties:{country:"USA", name:"Maroon 5", type:"Band"}}, {_id:58, properties:{country:"UK", imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTBwRJKiB14CwvX1zBd-rRa-VoAncwvd_0J0hpSSXNKeUNSnV3w&usqp=CAU", name:"Calvin Harris", type:"Solo"}}, {_id:60, properties:{country:"Sweden", imageUrl:"https://weraveyou.com/wp-content/uploads/2018/04/avicii.jpg", name:"Avicii", type:"Solo"}}, {_id:61, properties:{country:"USA", name:"Sublime", type:"Band"}}, {_id:63, properties:{country:"France", imageUrl:"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRqgH2MtNIHTJ_n2YiIJbRqJK70E1Woarlkr_NBmsUcxszPjEX-&usqp=CAU", name:"David Guetta", type:"Solo"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Artist;
UNWIND [{_id:0, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/1/19/Dr.DreTheChronic.jpg", year:1992, name:"The Chronic"}}, {_id:1, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/5/56/DrDre-2001.jpg", year:1999, name:"2001"}}, {_id:2, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Beyonc%C3%A9_-_B%27Day.png/220px-Beyonc%C3%A9_-_B%27Day.png", year:2006, name:"B'Day"}}, {_id:3, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/9/96/I_Am..._Sasha_Fierce.png", year:2008, name:"I Am... Sasha Fierce"}}, {_id:8, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/3/35/Shakira_-_Shakira_%282014%29.png", year:2014, name:"Shakira"}}, {_id:10, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Alleyezonme.jpg/220px-Alleyezonme.jpg", year:1996, name:"All Eyez on Me"}}, {_id:24, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/3/3d/Meagainsttheworldcover.jpg", year:1995, name:"Me Against the World"}}, {_id:30, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/c/ce/2Pac_Makaveli-The_Don_Killuminati_front.jpg", year:1996, name:"The Don Killuminati: The 7 Day Theory"}}, {_id:34, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/f/fb/Calvin_Harris_-_Motion.png", year:2014, name:"Motion"}}, {_id:35, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/d/df/Calvin_Harris_-_18_Months.png", year:2012, name:"18 Months"}}, {_id:49, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/6/63/SnoopDoggyDoggDoggystyle.jpg", year:1993, name:"Doggystyle"}}, {_id:52, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/a/a3/Tha-doggfather.jpg", year:1996, name:"Tha Doggfather"}}, {_id:54, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/b/b1/Bluecarpet.jpg", year:2006, name:"Tha Blue Carpet Treatment"}}, {_id:59, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/a/a3/Shakira_-_Sale_el_Sol_%28album_cover%29.jpg", year:2014, name:"Sale el Sol"}}, {_id:62, properties:{coverUrl:"https://en.wikipedia.org/wiki/File:Good_Girl_Gone_Bad.png", year:2007, name:"Good Girl Gone Bad"}}, {_id:64, properties:{coverUrl:"https://images-na.ssl-images-amazon.com/images/I/61uxgQJwLRL._SX522_.jpg", year:2013, name:"True"}}, {_id:65, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/c/c7/Avicii-Stories-2015-1200x1200.png", year:2015, name:"Stories"}}, {_id:66, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/a/ae/The_Marshall_Mathers_LP.jpg", year:2000, name:"The Marshall Mathers LP"}}, {_id:67, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/3/35/The_Eminem_Show.jpg", year:2002, name:"The Eminem Show"}}, {_id:68, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/4/42/David_Guetta_-_Nothing_but_the_Beat.png", year:2011, name:"Nothing but the Beat"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Album;
UNWIND [{_id:76, properties:{coverUrl:"https://en.wikipedia.org/wiki/Thriller_(album)#/media/File:Michael_Jackson_-_Thriller.png", year:1982, name:"Thriller"}}, {_id:77, properties:{coverUrl:"https://img.discogs.com/fnpKkvLW1meQzKAG_p2vVldkYzg=/fit-in/600x958/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1056450-1485381379-6654.jpeg.jpg", year:1987, name:"Bad"}}, {_id:78, properties:{coverUrl:"https://68.media.tumblr.com/ef26283b7a127049720b4c46a058b3f1/tumblr_inline_ohc240GKjz1qc4cgj_540.jpg", year:1991, name:"Dangerous"}}, {_id:79, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/6/60/Recovery_Album_Cover.jpg", year:2010, name:"Recovery"}}, {_id:80, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/commons/1/19/Famouscover1.jpg", year:2016, name:"The Life of Pablo"}}, {_id:81, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/f/f4/Late_registration_cd_cover.jpg", year:2005, name:"Late Registration"}}, {_id:83, properties:{coverUrl:"https://img.discogs.com/79WehP1UCYUrdoexfVf45kNNEh0=/fit-in/225x225/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2662996-1295546788.jpeg.jpg", year:2010, name:"One More Love"}}, {_id:84, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/9/9b/Unapologetic_-_Rihanna.png", year:2012, name:"Unapologetic"}}, {_id:85, properties:{coverUrl:"https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Rihanna_-_Loud.png/220px-Rihanna_-_Loud.png", year:2010, name:"Loud"}}] AS row
CREATE (n:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row._id}) SET n += row.properties SET n:Album;
:commit
:begin
UNWIND [{start: {_id:27}, end: {name:"Pop"}, properties:{}}, {start: {_id:28}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:32}, end: {name:"Hip-hop"}, properties:{}}, {start: {_id:44}, end: {name:"Hip-hop"}, properties:{}}, {start: {_id:33}, end: {name:"Pop"}, properties:{}}, {start: {_id:5}, end: {name:"Metal"}, properties:{}}, {start: {_id:53}, end: {name:"Hip-hop"}, properties:{}}, {start: {_id:56}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:29}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:31}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:23}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:50}, end: {name:"Metal"}, properties:{}}, {start: {_id:25}, end: {name:"Metal"}, properties:{}}, {start: {_id:51}, end: {name:"Hip-hop"}, properties:{}}, {start: {_id:55}, end: {name:"Pop"}, properties:{}}, {start: {_id:5}, end: {name:"Rock n roll"}, properties:{}}, {start: {_id:56}, end: {name:"Pop"}, properties:{}}, {start: {_id:63}, end: {name:"Electronic"}, properties:{}}, {start: {_id:60}, end: {name:"Electronic"}, properties:{}}, {start: {_id:61}, end: {name:"Rock n roll"}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:Genre{name: row.end.name})
CREATE (start)-[r:IS_GENRE]->(end) SET r += row.properties;
UNWIND [{start: {_id:45}, end: {name:"Hip-hop"}, properties:{}}, {start: {_id:46}, end: {name:"Reggae"}, properties:{}}, {start: {_id:47}, end: {name:"Reggae"}, properties:{}}, {start: {_id:7}, end: {name:"Reggae"}, properties:{}}, {start: {_id:48}, end: {name:"Pop"}, properties:{}}, {start: {_id:26}, end: {name:"Metal"}, properties:{}}, {start: {_id:58}, end: {name:"Electronic"}, properties:{}}, {start: {_id:61}, end: {name:"Reggae"}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:Genre{name: row.end.name})
CREATE (start)-[r:IS_GENRE]->(end) SET r += row.properties;
UNWIND [{start: {_id:82}, end: {_id:0}, properties:{}}, {start: {_id:86}, end: {_id:66}, properties:{}}, {start: {_id:87}, end: {_id:66}, properties:{}}, {start: {_id:88}, end: {_id:66}, properties:{}}, {start: {_id:89}, end: {_id:66}, properties:{}}, {start: {_id:90}, end: {_id:66}, properties:{}}, {start: {_id:91}, end: {_id:66}, properties:{}}, {start: {_id:92}, end: {_id:67}, properties:{}}, {start: {_id:93}, end: {_id:67}, properties:{}}, {start: {_id:94}, end: {_id:67}, properties:{}}, {start: {_id:95}, end: {_id:67}, properties:{}}, {start: {_id:96}, end: {_id:67}, properties:{}}, {start: {_id:97}, end: {_id:79}, properties:{}}, {start: {_id:98}, end: {_id:79}, properties:{}}, {start: {_id:99}, end: {_id:79}, properties:{}}, {start: {_id:100}, end: {_id:79}, properties:{}}, {start: {_id:101}, end: {_id:79}, properties:{}}, {start: {_id:102}, end: {_id:0}, properties:{}}, {start: {_id:103}, end: {_id:0}, properties:{}}, {start: {_id:104}, end: {_id:0}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:105}, end: {_id:0}, properties:{}}, {start: {_id:106}, end: {_id:1}, properties:{}}, {start: {_id:107}, end: {_id:1}, properties:{}}, {start: {_id:108}, end: {_id:1}, properties:{}}, {start: {_id:109}, end: {_id:1}, properties:{}}, {start: {_id:110}, end: {_id:1}, properties:{}}, {start: {_id:111}, end: {_id:49}, properties:{}}, {start: {_id:112}, end: {_id:49}, properties:{}}, {start: {_id:113}, end: {_id:49}, properties:{}}, {start: {_id:114}, end: {_id:49}, properties:{}}, {start: {_id:115}, end: {_id:49}, properties:{}}, {start: {_id:116}, end: {_id:52}, properties:{}}, {start: {_id:117}, end: {_id:52}, properties:{}}, {start: {_id:118}, end: {_id:52}, properties:{}}, {start: {_id:119}, end: {_id:52}, properties:{}}, {start: {_id:120}, end: {_id:52}, properties:{}}, {start: {_id:121}, end: {_id:54}, properties:{}}, {start: {_id:122}, end: {_id:54}, properties:{}}, {start: {_id:123}, end: {_id:54}, properties:{}}, {start: {_id:124}, end: {_id:54}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:125}, end: {_id:54}, properties:{}}, {start: {_id:126}, end: {_id:24}, properties:{}}, {start: {_id:127}, end: {_id:24}, properties:{}}, {start: {_id:128}, end: {_id:24}, properties:{}}, {start: {_id:129}, end: {_id:24}, properties:{}}, {start: {_id:130}, end: {_id:24}, properties:{}}, {start: {_id:131}, end: {_id:10}, properties:{}}, {start: {_id:132}, end: {_id:10}, properties:{}}, {start: {_id:133}, end: {_id:10}, properties:{}}, {start: {_id:134}, end: {_id:10}, properties:{}}, {start: {_id:135}, end: {_id:10}, properties:{}}, {start: {_id:136}, end: {_id:30}, properties:{}}, {start: {_id:137}, end: {_id:30}, properties:{}}, {start: {_id:138}, end: {_id:30}, properties:{}}, {start: {_id:139}, end: {_id:30}, properties:{}}, {start: {_id:140}, end: {_id:30}, properties:{}}, {start: {_id:141}, end: {_id:80}, properties:{}}, {start: {_id:142}, end: {_id:80}, properties:{}}, {start: {_id:143}, end: {_id:80}, properties:{}}, {start: {_id:144}, end: {_id:80}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:145}, end: {_id:80}, properties:{}}, {start: {_id:146}, end: {_id:81}, properties:{}}, {start: {_id:147}, end: {_id:81}, properties:{}}, {start: {_id:148}, end: {_id:81}, properties:{}}, {start: {_id:151}, end: {_id:68}, properties:{}}, {start: {_id:150}, end: {_id:68}, properties:{}}, {start: {_id:149}, end: {_id:68}, properties:{}}, {start: {_id:152}, end: {_id:68}, properties:{}}, {start: {_id:153}, end: {_id:68}, properties:{}}, {start: {_id:154}, end: {_id:68}, properties:{}}, {start: {_id:155}, end: {_id:83}, properties:{}}, {start: {_id:156}, end: {_id:83}, properties:{}}, {start: {_id:157}, end: {_id:81}, properties:{}}, {start: {_id:158}, end: {_id:81}, properties:{}}, {start: {_id:159}, end: {_id:35}, properties:{}}, {start: {_id:160}, end: {_id:35}, properties:{}}, {start: {_id:161}, end: {_id:35}, properties:{}}, {start: {_id:162}, end: {_id:35}, properties:{}}, {start: {_id:163}, end: {_id:35}, properties:{}}, {start: {_id:164}, end: {_id:83}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:165}, end: {_id:83}, properties:{}}, {start: {_id:166}, end: {_id:83}, properties:{}}, {start: {_id:167}, end: {_id:34}, properties:{}}, {start: {_id:168}, end: {_id:34}, properties:{}}, {start: {_id:169}, end: {_id:34}, properties:{}}, {start: {_id:170}, end: {_id:34}, properties:{}}, {start: {_id:171}, end: {_id:34}, properties:{}}, {start: {_id:172}, end: {_id:64}, properties:{}}, {start: {_id:173}, end: {_id:64}, properties:{}}, {start: {_id:174}, end: {_id:64}, properties:{}}, {start: {_id:175}, end: {_id:64}, properties:{}}, {start: {_id:176}, end: {_id:64}, properties:{}}, {start: {_id:177}, end: {_id:65}, properties:{}}, {start: {_id:178}, end: {_id:65}, properties:{}}, {start: {_id:179}, end: {_id:65}, properties:{}}, {start: {_id:180}, end: {_id:65}, properties:{}}, {start: {_id:181}, end: {_id:65}, properties:{}}, {start: {_id:182}, end: {_id:84}, properties:{}}, {start: {_id:183}, end: {_id:84}, properties:{}}, {start: {_id:185}, end: {_id:84}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:184}, end: {_id:84}, properties:{}}, {start: {_id:186}, end: {_id:84}, properties:{}}, {start: {_id:187}, end: {_id:84}, properties:{}}, {start: {_id:188}, end: {_id:85}, properties:{}}, {start: {_id:190}, end: {_id:85}, properties:{}}, {start: {_id:189}, end: {_id:85}, properties:{}}, {start: {_id:191}, end: {_id:85}, properties:{}}, {start: {_id:192}, end: {_id:85}, properties:{}}, {start: {_id:193}, end: {_id:62}, properties:{}}, {start: {_id:194}, end: {_id:62}, properties:{}}, {start: {_id:195}, end: {_id:62}, properties:{}}, {start: {_id:196}, end: {_id:62}, properties:{}}, {start: {_id:197}, end: {_id:62}, properties:{}}, {start: {_id:198}, end: {_id:76}, properties:{}}, {start: {_id:199}, end: {_id:76}, properties:{}}, {start: {_id:200}, end: {_id:76}, properties:{}}, {start: {_id:201}, end: {_id:76}, properties:{}}, {start: {_id:202}, end: {_id:76}, properties:{}}, {start: {_id:203}, end: {_id:77}, properties:{}}, {start: {_id:204}, end: {_id:77}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:205}, end: {_id:77}, properties:{}}, {start: {_id:206}, end: {_id:77}, properties:{}}, {start: {_id:207}, end: {_id:77}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FROM_ALBUM]->(end) SET r += row.properties;
UNWIND [{start: {_id:87}, end: {_id:53}, properties:{}}, {start: {_id:87}, end: {_id:51}, properties:{}}, {start: {_id:93}, end: {_id:51}, properties:{}}, {start: {_id:98}, end: {_id:33}, properties:{}}, {start: {_id:82}, end: {_id:53}, properties:{}}, {start: {_id:102}, end: {_id:53}, properties:{}}, {start: {_id:104}, end: {_id:53}, properties:{}}, {start: {_id:106}, end: {_id:53}, properties:{}}, {start: {_id:107}, end: {_id:32}, properties:{}}, {start: {_id:108}, end: {_id:53}, properties:{}}, {start: {_id:109}, end: {_id:32}, properties:{}}, {start: {_id:112}, end: {_id:51}, properties:{}}, {start: {_id:132}, end: {_id:51}, properties:{}}, {start: {_id:133}, end: {_id:53}, properties:{}}, {start: {_id:134}, end: {_id:53}, properties:{}}, {start: {_id:141}, end: {_id:33}, properties:{}}, {start: {_id:146}, end: {_id:56}, properties:{}}, {start: {_id:149}, end: {_id:53}, properties:{}}, {start: {_id:182}, end: {_id:32}, properties:{}}, {start: {_id:183}, end: {_id:63}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FEATURING]->(end) SET r += row.properties;
UNWIND [{start: {_id:202}, end: {_id:23}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:FEATURING]->(end) SET r += row.properties;
UNWIND [{start: {_id:0}, end: {_id:51}, properties:{}}, {start: {_id:1}, end: {_id:51}, properties:{}}, {start: {_id:10}, end: {_id:45}, properties:{}}, {start: {_id:24}, end: {_id:45}, properties:{}}, {start: {_id:30}, end: {_id:45}, properties:{}}, {start: {_id:49}, end: {_id:53}, properties:{}}, {start: {_id:52}, end: {_id:53}, properties:{}}, {start: {_id:54}, end: {_id:53}, properties:{}}, {start: {_id:34}, end: {_id:58}, properties:{}}, {start: {_id:35}, end: {_id:58}, properties:{}}, {start: {_id:2}, end: {_id:55}, properties:{}}, {start: {_id:3}, end: {_id:55}, properties:{}}, {start: {_id:8}, end: {_id:48}, properties:{}}, {start: {_id:59}, end: {_id:48}, properties:{}}, {start: {_id:62}, end: {_id:33}, properties:{}}, {start: {_id:84}, end: {_id:33}, properties:{}}, {start: {_id:85}, end: {_id:33}, properties:{}}, {start: {_id:76}, end: {_id:27}, properties:{}}, {start: {_id:78}, end: {_id:27}, properties:{}}, {start: {_id:81}, end: {_id:44}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:BY_ARTIST]->(end) SET r += row.properties;
UNWIND [{start: {_id:77}, end: {_id:27}, properties:{}}, {start: {_id:64}, end: {_id:60}, properties:{}}, {start: {_id:65}, end: {_id:60}, properties:{}}, {start: {_id:66}, end: {_id:32}, properties:{}}, {start: {_id:67}, end: {_id:32}, properties:{}}, {start: {_id:79}, end: {_id:32}, properties:{}}, {start: {_id:80}, end: {_id:44}, properties:{}}, {start: {_id:68}, end: {_id:63}, properties:{}}, {start: {_id:83}, end: {_id:63}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.end._id})
CREATE (start)-[r:BY_ARTIST]->(end) SET r += row.properties;
UNWIND [{start: {_id:9}, end: {name:"Metal"}, properties:{}}, {start: {_id:9}, end: {name:"Reggae"}, properties:{}}] AS row
MATCH (start:`UNIQUE IMPORT LABEL`{`UNIQUE IMPORT ID`: row.start._id})
MATCH (end:Genre{name: row.end.name})
CREATE (start)-[r:HAS_FAVORITE_GENRE]->(end) SET r += row.properties;
:commit
:begin
MATCH (n:`UNIQUE IMPORT LABEL`)  WITH n LIMIT 20000 REMOVE n:`UNIQUE IMPORT LABEL` REMOVE n.`UNIQUE IMPORT ID`;
:commit
:begin
DROP CONSTRAINT ON (node:`UNIQUE IMPORT LABEL`) ASSERT (node.`UNIQUE IMPORT ID`) IS UNIQUE;
:commit
